version: '3'
services:
  runner:
    build: 
      context: .
      args:
        DOCKER_GROUP_ID: ${DOCKER_GROUP_ID}
    restart: unless-stopped
    environment:
      ACCESS_TOKEN: ${ACCESS_TOKEN}
      OWNER: ${OWNER}
      REPO: ${REPO}
    deploy:
      replicas: 4